{% set name = "maxvolpy" %}
{% set version = "0.3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/maxvolpy-{{ version }}.tar.gz
  sha256: df4adb1bbc091e960ec5f3e5b53c3909ae428f5e48cf7ab95a01ea982a1a1980

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 3
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - cython
    - numpy
    - pip
    - libblas
    - liblapack
  run:
    - python
    - cython >=0.23.4

test:
  imports:
    - maxvolpy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://bitbucket.org/muxas/maxvolpy
  summary: Cross and skeleton approximations, based on maximum volume submatrices.
  doc_url: https://pythonhosted.org/maxvolpy/
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jan-janssen
